set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN V10 [get_ports in]
set_property PACKAGE_PIN V11 [get_ports out]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports in]
set_property IOSTANDARD LVCMOS33 [get_ports out]
